# Primeira Avaliação Parcial: Avaliação Individual

Neste módulo trabalhamos com os recursos da __NumPy__ para processar dados de tipo único de forma eficiente. Um exemplo deste tipo de dados são as imagens que podemos ser armazenadas como _ndarrays_ __NumPy__. O código a seguir gera uma imagem colorida, de 1000 por 1000 _pixels_, armazenada no formato __RGB__. Isto significa que, de cada _pixel_ armazenamos a intensidade de cor nos canais __R__ (_red_ ou vermelho), __G__ (green ou verde) e __B__ (blue o azul).  A intensidade da cor é dada por um inteiro de 8 _bits_ sem sinal.

In [56]:
# importado a biblioteca numpy
import numpy as np
print(np.__version__)

1.21.5


In [57]:
# Definindo a altura e a largura da imagem
height = 1000  # altura ou o número de linhas da imagem
width = 1000   # largura ou o número de colunas da imagem

In [58]:
# gerando uma imagem aleatória de 1000 x 1000 pixels
random_image = np.random.randint(0, 256, size=(height, width, 3), dtype=np.uint8)
print("Veja o forma da matriz criada: {}".format(random_image.shape))
print("Veja como fica a cor de um pixel: {} ...".format(random_image[0, 0]))
print("Ou a componente vermelha dos 3 primeiro pixels da segunda linha: {} ...".format(random_image[1, 0:3, 0]))
print("Ou a componente verde dos 3 últimos pixels da segunda coluna: {} ...".format(random_image[-3:, 1, 1]))

print(random_image)

Veja o forma da matriz criada: (1000, 1000, 3)
Veja como fica a cor de um pixel: [ 72 229 137] ...
Ou a componente vermelha dos 3 primeiro pixels da segunda linha: [228   8  37] ...
Ou a componente verde dos 3 últimos pixels da segunda coluna: [ 95 143 203] ...
[[[ 72 229 137]
  [ 88 154  25]
  [ 36  13 164]
  ...
  [ 52 253  11]
  [175 168 218]
  [ 74 240  62]]

 [[228 134 183]
  [  8  22 149]
  [ 37  50  95]
  ...
  [ 22  22  95]
  [128 143 158]
  [ 11   1 193]]

 [[214  99 255]
  [110 203  23]
  [180  29 218]
  ...
  [196   9 149]
  [194  73  83]
  [175   1 161]]

 ...

 [[119  64 160]
  [ 27  95 109]
  [110 170  72]
  ...
  [ 89  56  91]
  [ 31  93 111]
  [ 90   4 139]]

 [[150 163  57]
  [114 143 250]
  [173  66  54]
  ...
  [134 109 127]
  [206  94  57]
  [170 177  53]]

 [[147  88 212]
  [178 203 132]
  [248 214 151]
  ...
  [237  96 207]
  [ 97 126 149]
  [111 133 167]]]


## Exercício 1

Crie uma função para a qual passamos como parâmetros a altura e a largura e retorna uma imagem, gerada de forma aleatória, em formato __RGB__, com estas dimensões. A imagem deve ser representada utilizando um _ndarray_ como o do exemplo anterior. Se a altura ou a largura não forme passadas como a imagem deve ser gerada com 720 linhas e 1280 colunas. 

In [59]:
# Implementar aqui
def geradorImagens(ImgHeight= 720,imgWidth = 1280):
    random_image = np.random.randint(0, 256, size=(ImgHeight, imgWidth, 3), dtype=np.uint8)
    return random_image


In [60]:
#teste
print(geradorImagens().shape) # deve retornar (720, 1280, 3)
print(geradorImagens(10,1280).shape) # deve retornar (10, 1280, 3)
print(geradorImagens(10,10).shape) # deve retornar (10, 10, 3)
print(geradorImagens(5,5)) # deve retornar uma matriz 5x5x3

(720, 1280, 3)
(10, 1280, 3)
(10, 10, 3)
[[[235 151 118]
  [  9  64 136]
  [157  43 230]
  [237 123 135]
  [ 21  44  32]]

 [[187 224 195]
  [202 115  63]
  [ 11 181 227]
  [143 126  87]
  [ 61  94 162]]

 [[154  18 229]
  [142  73 104]
  [124   3 195]
  [ 30 131 190]
  [166 203 188]]

 [[207  15 101]
  [149 139   5]
  [132 247 115]
  [ 61 215 202]
  [ 26  30  62]]

 [[231 112 155]
  [110   5 182]
  [236  22   6]
  [184 162 212]
  [218 127  86]]]


Para simplificar o tratamento durante o processamento das imagens, frequentemente elas são convertidas e imagens em tons de cinza. Estas imagens contem, para cada pixel, uma única intensidade de cor representada como um inteiro de 8 _bits_ sem sinal. Para converter uma imagem __RGB__ em uma imagem em tons de cinza podemos utilizar dois métodos diferentes. 

1. Calculamos a intensidade da cor de cada _pixel_ como a média das intensidades dos canais __RGB_
2. Os valores __RGB__ são convertidos para tons de cinza usando a fórmula __NTSC__: $ 0.299 \times \text{Vermelho} + 0.587 \times \text{Verde} + 0.114 \times \text{Azul} $. Esta fórmula representa de perto a percepção relativa da pessoa média sobre o brilho da luz vermelha, verde e azul.

## Exercício 2

Crie uma função que recebe uma imagem __RGB__ e converte a mesma em tons de cinza. A função deve retornar então a nova imagem. Esta função. 
* Deve verificar se o argumento de entrada é de fato uma imagem __RGB__ com base no tipo e no atributo ``shape`` do _ndarray_. Casso o argumento esteja errado deve-se lançar uma exceção.
* A função recebe como parâmetro de entrada a forma de conversão a ser utilizada: media dos canais ou __NTSC__. Por padrão o algoritmo de utilizado deve ser o __NTSC__.
* A função deve utilizas as _ufunc_ e operações definidas na __NumPy_ de forma a minimizar o uso de laços no processamento dos _ndarrays_.  

In [61]:
#implementar aqui
def rgb2gray(imagem, metConversao='NTSC'):
    
    # verifico se a imagem veio em ndarray e com 3 dimensões (RGB)
    if not isinstance(imagem, np.ndarray) or imagem.ndim != 3 or imagem.shape[2] != 3:
        raise ValueError("O parametro informado não é compatível a uma imagem RGB.")

    # converte usando a o método de Media ou NTSC
    if metConversao == 'media':
        # axis: eixo 2 ou canais, uint8: do tipo inteiro 8 bits 
        imagem_cinza = np.mean(imagem, axis=2, dtype=np.uint8)
    elif metConversao == 'NTSC':
        ntsc_coefs = np.array([0.299, 0.587, 0.114])
        # np.dot: multiplicação de matrizes ou produtos internos (produtos escalar ou ponto) entre vetores, neste caso entre o ndarray e o ntsc_coefs
        imagem_cinza = np.dot(imagem, ntsc_coefs)
        #  converte os valores resultantes para uint8
        imagem_cinza = imagem_cinza.astype(np.uint8)
    else:
        raise ValueError("Método de conversão inválido. Escolha 'media' ou 'NTSC'.")

    return imagem_cinza


imagemExemplo = geradorImagens()
print("Imagem original\n")
print(imagemExemplo)

imagemEmGray = rgb2gray(imagemExemplo)
print("Imagem modificado p/ tons de cinza \n")
print(imagemEmGray)

Imagem original

[[[131 156 248]
  [120 162 181]
  [247 191  26]
  ...
  [170 144 228]
  [ 47  94 210]
  [ 74   9  95]]

 [[129  14 125]
  [ 84 155 139]
  [224  22 125]
  ...
  [183 127  93]
  [113 231 153]
  [ 67 161   7]]

 [[255 199 176]
  [111 135  20]
  [150   6  99]
  ...
  [161  91 208]
  [213 157 240]
  [ 13 183 135]]

 ...

 [[193 149  79]
  [ 30 147 195]
  [118 187 255]
  ...
  [ 92  99   0]
  [199 177  44]
  [200 128  88]]

 [[149 173 151]
  [ 89   7 134]
  [ 50 215 235]
  ...
  [175 191 123]
  [ 75 134   4]
  [153  18 245]]

 [[ 66 131 124]
  [ 65  83 184]
  [201  81 116]
  ...
  [ 91 248 164]
  [146  37  16]
  [ 44  71  21]]]
Imagem modificado p/ tons de cinza 

(720, 1280)


# Exercício 3 (Opcional, valendo ponto extra)

Refaça a implementação da função anterior utilizando estruturas de repetição e implemente um teste de demonstre, usando uma imagem __RGB__ gerada de forma aleatória de 10.000 linhas por 10.000 colunas, o ganho de desempenho quando utilizamos as _ufunc_ e os operadores de __NumPy__. 

In [ ]:
def rgb2grayComLacos(imagem, metodo_conversao='NTSC'):
    
    if not isinstance(imagem, np.ndarray) or imagem.ndim != 3 or imagem.shape[2] != 3:
        raise ValueError("O parametro informado não é compatível a uma imagem RGB.")

    altura, largura, _ = imagem.shape
    imagem_cinza = np.empty((altura, largura), dtype=np.uint8)

    if metodo_conversao == 'media':
        for i in range(altura):
            for j in range(largura):
                imagem_cinza[i, j] = np.mean(imagem[i, j, :]).astype(np.uint8)
    elif metodo_conversao == 'NTSC':
        ntsc_coefs = np.array([0.299, 0.587, 0.114])
        for i in range(altura):
            for j in range(largura):
                imagem_cinza[i, j] = np.dot(imagem[i, j, :], ntsc_coefs).astype(np.uint8)
    else:
        raise ValueError("Método de conversão inválido. Escolha 'media' ou 'NTSC'.")

    return imagem_cinza


## Respostas
Faça suas implementações neste notebook e envie  mesmo via __Moodle__ até o final do prazo. 